{{ if .Values.alerts.enabled }}
---
apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: {{ include "azurerator.fullname" . }}-alerts
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
spec:
  receivers:
    slack:
      channel: "{{ .Values.alerts.slackChannel }}"
  alerts:
    - alert: {{ include "azurerator.fullname" . }} failed provisioning clients in {{ .Values.clusterName }}
      expr: sum(rate(azureadapp_failed_processing_count{app="{{ include "azurerator.fullname" . }}"}[5m])) > 0
      for: 5m
      description: "{{ include "azurerator.fullname" . }} has failed processing clients for longer than usual\n\nConsequence: applications that have azure.application enabled will not start up as they are dependant on a secret created by Azurerator.\n"
      action: "Check logs:\n- `kubectl logs -n nais deploy/{{ include "azurerator.fullname" . }}`"
      sla: respond within office hours
      severity: danger
{{ end }}
