{{ if .Values.global.alerts.enabled | default .Values.alerts.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "azurerator.fullname" . }}-alerts
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
spec:
  groups:
    - name: "azurerator"
      rules:
        - alert: {{ include "azurerator.fullname" . }} failed provisioning clients
          expr: sum(increase(azureadapp_failed_processing_count{app="{{ include "azurerator.fullname" . }}"}[5m])) > {{ .Values.global.alerts.failedProcessingThreshold | default .Values.alerts.failedProcessingThreshold }}
          for: 5m
          annotations:
            summary: {{ include "azurerator.fullname" . }} has failed processing clients for longer than usual
            consequence: Applications that have spec.azure.application enabled will not start up as they are dependant on a secret created by Azurerator
            action: |
              * Check the logs: `kubectl logs -n {{ .Release.Namespace }} deploy/{{ include "azurerator.fullname" . }}`"
              * Check the Azure Status page: <https://azure.status.microsoft/status>
          labels:
            severity: critical
            namespace: {{ .Release.Namespace }}
{{ end }}
