---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ include "azurerator.fullname" . }}
  labels:
    team: nais
    {{ include "azurerator.labels" . | nindent 4 }}
spec:
  image: "{{ .Values.global.image.repository | default .Values.image.repository }}:{{ .Values.global.image.tag | default .Values.image.tag }}"
  port: 8080
  liveness:
    path: /metrics
  readiness:
    path: /metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 512Mi
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  filesFrom:
    - secret: {{ include "azurerator.fullname" . }}-env
      mountPath: /etc/azurerator
  accessPolicy:
    inbound:
      rules:
        - application: prometheus
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: graph.microsoft.com
  {{- if .Values.global.kafka.application | default .Values.kafka.application }}
  kafka:
    pool: "{{ .Values.global.kafka.pool | default .Values.kafka.pool }}"
  {{ end }}
  webproxy: {{ .Values.global.webproxy | default .Values.webproxy }}
