{{ if .Values.global.networkPolicy.enabled | default .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "azurerator.fullname" . }}-apiserver
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
spec:
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.global.networkPolicy.apiServerCIDR | default .Values.networkPolicy.apiServerCIDR }}
  podSelector:
    matchLabels:
      {{ include "azurerator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
{{ end }}
