{{ if .Values.global.networkPolicy.enabled | default .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "azurerator.fullname" . }}-apiserver
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
spec:
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.global.networkPolicy.apiServerCIDR | default .Values.networkPolicy.apiServerCIDR }}
    - ports:
        - port: 443
          protocol: TCP
      to:
        # selected microsoft login ranges (https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online)
        - ipBlock:
            cidr: 20.190.128.0/18
        - ipBlock:
            cidr: 40.126.0.0/18
        - ipBlock:
            cidr: 20.20.32.0/19
        - ipBlock:
            cidr: 20.231.128.0/19
  podSelector:
    matchLabels:
      {{ include "azurerator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
{{ end }}
