---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
  name: {{ include "azurerator.fullname" . }}
rules:
  - apiGroups:
      - nais.io
    resources:
      - azureadapplications
      - azureadapplications/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - list
      - get
      - watch

---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "azurerator.fullname" . }}-leader-election
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "azurerator.fullname" . }}
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "azurerator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "azurerator.fullname" . }}
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
  name: {{ include "azurerator.fullname" . }}-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "azurerator.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "azurerator.fullname" . }}
    namespace: "{{ .Release.Namespace }}"
