---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "azurerator.fullname" . }}-env
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
stringData:
  azurerator.yaml: |
    azure:
      auth:
        client-id: "{{ .Values.azure.clientID }}"
        client-secret: "{{ .Values.azure.clientSecret }}"
      features:
        app-role-assignment-required:
          enabled: "{{ .Values.features.appRoleAssignmentRequired }}"
        claims-mapping-policies:
          enabled: "{{ .Values.features.claimsMappingPolicies.enabled }}"
          id: "{{ .Values.features.claimsMappingPolicies.id }}"
        cleanup-orphans:
          enabled: "{{ .Values.features.cleanupOrphans }}"
        groups-assignment:
          enabled: "{{ .Values.features.groupsAssignment.enabled }}"
          {{- if .Values.features.groupsAssignment.allUsersGroupIDs }}
          all-users-group-id:
            {{- range $val := .Values.features.groupsAssignment.allUsersGroupIDs }}
            - "{{ $val }}"
            {{- end }}
          {{- end }}
      permissiongrant-resource-id: "{{ .Values.azure.permissionGrantResourceID }}"
      tenant:
        id: "{{ .Values.azure.tenant.id }}"
        name: "{{ .Values.azure.tenant.name }}"
    cluster-name: "{{ .Values.clusterName }}"
    controller:
      max-concurrent-reconciles: "{{ .Values.controller.maxConcurrentReconciles }}"
    kafka:
      enabled: "{{ .Values.kafka.application.enabled }}"
      topic: "{{ .Values.kafka.topic.namespace }}.{{ .Values.kafka.topic.name }}"
      tls:
        enabled: "{{ .Values.kafka.tls }}"
    leader-election:
      enabled: "{{ .Values.controller.leaderElection }}"
    secret-rotation:
      cleanup: "{{ .Values.controller.secretRotation }}"
    validations:
      tenant:
        required: "{{ .Values.controller.tenantNameStrictMatching }}"
