---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "azurerator.fullname" . }}-env
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
stringData:
  azurerator.yaml: |
    azure:
      auth:
        client-id: "{{ .Values.azure.clientID | required ".Values.azure.clientID is required." }}"
        {{- if .Values.global.google.federatedAuth | default .Values.google.federatedAuth }}
        client-secret: "{{ .Values.azure.clientSecret | default "n/a" }}"
        {{ else }}
        client-secret: "{{ .Values.azure.clientSecret | required ".Values.azure.clientSecret is required." }}"
        {{ end }}
        {{- if .Values.global.google.federatedAuth | default .Values.google.federatedAuth }}
        google:
          enabled: "{{ .Values.global.google.federatedAuth | default .Values.google.federatedAuth }}"
          project-id: "{{ .Values.global.google.projectID | default .Values.google.projectID | required ".Values.google.projectID is required." }}"
        {{ end }}
      features:
        app-role-assignment-required:
          enabled: "{{ .Values.global.features.appRoleAssignmentRequired | default .Values.features.appRoleAssignmentRequired }}"
        claims-mapping-policies:
          enabled: "{{ .Values.global.features.claimsMappingPolicies.enabled | default .Values.features.claimsMappingPolicies.enabled }}"
          id: "{{ .Values.features.claimsMappingPolicies.id }}"
        cleanup-orphans:
          enabled: "{{ .Values.global.features.cleanupOrphans | default .Values.features.cleanupOrphans }}"
        custom-security-attributes:
          enabled: "{{ .Values.global.features.customSecurityAttributes.enabled | default .Values.features.customSecurityAttributes.enabled }}"
        groups-assignment:
          enabled: "{{ .Values.global.features.groupsAssignment.enabled | default .Values.features.groupsAssignment.enabled }}"
          {{- if .Values.features.groupsAssignment.allUsersGroupIDs }}
          all-users-group-id:
            {{- range $val := .Values.features.groupsAssignment.allUsersGroupIDs }}
            - "{{ $val }}"
            {{- end }}
          {{- end }}
      permissiongrant-resource-id: "{{ .Values.azure.permissionGrantResourceID | required ".Values.azure.permissionGrantResourceID is required." }}"
      tenant:
        id: "{{ .Values.azure.tenant.id | required ".Values.azure.tenant.id is required." }}"
        name: "{{ .Values.azure.tenant.name | required ".Values.azure.tenant.name is required." }}"
    cluster-name: "{{ .Values.global.clusterName | default .Values.clusterName | required ".Values.clusterName is required." }}"
    controller:
      max-concurrent-reconciles: "{{ .Values.global.controller.maxConcurrentReconciles | default .Values.controller.maxConcurrentReconciles }}"
    kafka:
      enabled: "{{ .Values.global.kafka.application | default .Values.kafka.application }}"
      topic: "{{ .Release.Namespace }}.{{ include "azurerator.fullname" . }}"
      tls:
        enabled: "{{ .Values.global.kafka.tls | default .Values.kafka.tls }}"
    leader-election:
      enabled: "{{ .Values.global.controller.leaderElection | default .Values.controller.leaderElection }}"
    secret-rotation:
      cleanup: "{{ .Values.global.controller.secretRotation | default .Values.controller.secretRotation }}"
      max-age: "{{ .Values.global.controller.secretRotationMaxAge | default .Values.controller.secretRotationMaxAge }}"
    validations:
      tenant:
        required: "{{ .Values.controller.tenantNameStrictMatching }}"
