{{ if .Values.global.kafka.topic | default .Values.kafka.topic }}
---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: {{ include "azurerator.fullname" . }}
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
spec:
  acl:
    - access: readwrite
      application: {{ include "azurerator.fullname" . }}
      team: {{ .Release.Namespace }}
  pool: {{ .Values.global.kafka.pool | default .Values.kafka.pool }}
{{ end }}
