{{ if .Values.kafka.topic.create }}
---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: {{ .Values.kafka.topic.name }}
  namespace: {{ .Values.kafka.topic.namespace }}
  labels:
    {{ include "azurerator.labels" . | nindent 4 }}
spec:
  acl:
    - access: readwrite
      application: {{ include "azurerator.fullname" . }}
      team: {{ .Release.Namespace }}
  {{- range $val := .Values.kafka.topic.acl }}
    - access: readwrite
      application: {{ $val.application }}
      team: {{ $val.team }}
  {{- end }}
  pool: {{ .Values.kafka.pool }}
{{ end }}
