# permissions for end users to edit azureadapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azureadapplication-editor-role
rules:
- apiGroups:
  - nais.io
  resources:
  - azureadapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nais.io
  resources:
  - azureadapplications/status
  verbs:
  - get
