# permissions for end users to edit azureadcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azureadcredential-editor-role
rules:
- apiGroups:
  - nais.io
  resources:
  - azureadcredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nais.io
  resources:
  - azureadcredentials/status
  verbs:
  - get
