---
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: myapp
  namespace: default
  labels:
    team: myteam
spec:
  preAuthorizedApplications:
    - application: myapp2
      cluster: minikube
      namespace: default
    - application: some-other-app
      cluster: test-cluster
      namespace: default
  logoutUrl: "https://localhost:3000/oauth2/logout"
  replyUrls:
    - url: "http://localhost:3000/oauth2/callback"
  secretName: azuread-myapp2
