---
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: myapp
  namespace: myteam
  labels:
    team: myteam
spec:
  # required
  secretName: azuread-myapp
  # everything below is optional
  claims:
    extra:
      - "NAVident"
    groups:
      - id: "00000000-0000-0000-0000-000000000000"
  logoutUrl: "https://localhost:3000/oauth2/logout"
  preAuthorizedApplications:
    - application: myapp2
      cluster: minikube
      namespace: myteam
    - application: some-other-app
      cluster: test-cluster
      namespace: myteam
  replyUrls:
    - url: "http://localhost:3000/oauth2/callback"
  secretKeyPrefix: "" # defaults to 'AZURE' if empty or undefined
  tenant: local.test
