---
apiVersion: nais.io/v1alpha1
kind: AzureAdCredential
metadata:
  name: myapp
  namespace: default
  labels:
    team: myteam
spec:
  preAuthorizedApplications:
    - name: myapp-frontend
    - name: some-other-app
      clientId: some-client-id
  replyUrls:
    - url: "http://localhost:3000/oauth2/callback"
