---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: azurerator
  name: azurerator
rules:
  - apiGroups:
      - nais.io
    resources:
      - azureadapplications
      - azureadapplications/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - '*'
    resources:
      - secrets
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - '*'
    resources:
      - pods
      - namespaces
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: azurerator
  name: azurerator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azurerator
subjects:
  - kind: ServiceAccount
    name: azurerator
    namespace: azurerator-system
